<?php

/**
 * Naipunya Enterprise Service Management
 * Copyright (C) 2026 Naipunya Tax and Accounting Solutions Pvt.Ltd.
 */

namespace Glpi\Asset\CustomFieldOption;

use InvalidArgumentException;

interface OptionInterface
{
    /**
     * Get the option name.
     */
    public function getName(): string;

    /**
     * Get the option key.
     */
    public function getKey(): string;

    /**
     * Defines configured value.
     */
    public function setValue(mixed $value): void;

    /**
     * Get the configured value.
     */
    public function getValue(): mixed;

    /**
     * Get the HTML code to use to display the option input in the custom field form.
     */
    public function getFormInput(): string;

    /**
     * Normalize the value submitted using the input generated by `self::getFormInput()`.
     *
     * @param mixed $value
     * @throws InvalidArgumentException Thrown if the submitted value does not correspond to a valid value.
     */
    public function normalizeValue(mixed $value): mixed;

    /**
     * @return bool True if this option should be applied to the default value field
     */
    public function getApplyToDefault(): bool;
}
