<?php

/**
 * Naipunya Enterprise Service Management
 * Copyright (C) 2026 Naipunya Tax and Accounting Solutions Pvt.Ltd.
 */

namespace Glpi\Asset\CustomFieldType;

use Glpi\Asset\CustomFieldOption\OptionInterface;
use InvalidArgumentException;

interface TypeInterface
{
    public static function isAllowedForCustomFields(): bool;

    /**
     * Get the field type name.
     */
    public static function getName(): string;

    public function getLabel(): string;

    /**
     * Get the HTML code to use to display the custom field input in the asset form.
     *
     *
     * @param string $name          The field `name` attribute
     * @param mixed $value          The field current value
     * @param string|null $label    The custom label to use, fallback to the label defined in the field definition
     * @param bool $for_default     Indicates whether the field is used to configure the default value of the field definition
     * @return string
     */
    public function getFormInput(string $name, mixed $value, ?string $label = null, bool $for_default = false): string;

    /**
     * Normalize the value submitted using the input generated by `self::getFormInput()`.
     *
     * @param mixed $value
     * @throws InvalidArgumentException Thrown if the submitted value does not correspond to a valid value.
     */
    public function normalizeValue(mixed $value): mixed;

    /**
     * Format the value before it is saved in the database.
     * Automatically calls `self::normalizeValue()` before formatting the value.
     *
     * @param mixed $value
     * @return mixed
     */
    public function formatValueForDB(mixed $value): mixed;

    /**
     * Format the value after it is read from the database.
     *
     * @param mixed $value
     */
    public function formatValueFromDB(mixed $value): mixed;

    /**
     * Get the field options.
     *
     * @return OptionInterface[]
     */
    public function getOptions(): array;

    /**
     * @return array<string, mixed>
     */
    public function getOptionValues(bool $default_field = false): array;

    /**
     * Defines configured default value.
     */
    public function setDefaultValue(mixed $value): void;

    /**
     * Get the configured default value.
     */
    public function getDefaultValue(): mixed;

    /**
     * Get the HTML code to use to display the default value input in the configuration form.
     */
    public function getDefaultValueFormInput(): string;

    /**
     * Get the field search option specs to be added to the result of `\Glpi\Asset\Asset::rawSearchOptions()`.
     */
    public function getSearchOption(): ?array;
}
